config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "bookmarks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
 	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :get_categories, only: [:index, :new,:edit]

  def index
    @bookmark = Bookmark.new
    if params[:q].present?
      query = Bookmark.where("title LIKE ? OR host LIKE ? OR url LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
      @bookmarks = query.includes(:category).map { |bookmark| bookmark.as_json.merge({category: bookmark.category.try(:name)}) } 
      render json: @bookmarks
    else
      @bookmarks = Bookmark.includes(:category).map { |bookmark| bookmark.as_json.merge({category: bookmark.category.try(:name)}) } 
    end
  end

  def new
    @bookmark = Bookmark.new
  end

  def edit
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      render json: @bookmark.as_json.merge({category: @bookmark.category.try(:name)}) 
    else
      render json: @bookmark.errors, status: :unprocessable_entity
    end
  end


  def update
    category = Category.where(:name => params[:bookmark][:category_id].capitalize).first
    params[:bookmark][:category_id] = category.id
    if @bookmark.update(bookmark_params)
      render json: @bookmark.as_json.merge({category: category.try(:name)}) 
    else
      render json: @bookmark.errors, status: :unprocessable_entity
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    def get_categories
      @categories = Category.all
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:host, :url, :title, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bookmarks.html.erb
<h1>Bookmarks</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Host</th>
      <th>Url</th>
      <th>Title</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.host %></td>
        <td><%= bookmark.url %></td>
        <td><%= bookmark.title %></td>
        <td><%= bookmark.category.name %></td>
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark, html: {class: "form-inline"}) do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
    <%= f.input :title, class: 'form-control', style: "width:250px;"%>
  </div>
  <div class="form-group">
    <%= f.input :host, class: 'form-control', style: "width:250px;"%>
  </div>
  <div class="form-group">
    <%= f.input :url, class: 'form-control', style: "width:250px;"%>
  </div>
  <div class="form-group">
    <%= f.input :category_id, as: :select, options_for_select(@categories, :id, :name, :id) class: 'form-control', style: "width:250px;"%>
  </div>
  <div class="form-actions">
    <%= f.submit "#{action_name.capitalize} Bookmark"%>
    <%= link_to 'Cancel', bookmarks_path, class: "btn btn-danger btn-min" %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

app/views/bookmarks/index.html.erb
<center><h1>Bookmarks Management</h1></center>

<%= react_component("Bookmarks", {bookmarks: @bookmarks, categories: @categories})%>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<div class="container">
<p>
  <strong>Host:</strong>
  <%= @bookmark.host %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @bookmark.category.name %>
</p>

<%= link_to 'Back', bookmarks_path, class: "btn btn-primary btn-min" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>